---
version: "3.8"

x-service: &default-service
  environment:
    - ENVIRONMENT=Docker
  ports:
      - "4040:4040"
  networks:
    - sokka_network

services:
  server:
    <<: *default-service
    container_name: sokka_server
    build:
      context: .
      dockerfile: src/Server/Dockerfile

  client:
    <<: *default-service
    container_name: sokka_client
    build:
      context: .
      dockerfile: src/Client/Dockerfile

networks:
  sokka_network:
