---
version: "3.8"

x-service: &default-service
  environment:
    - ENVIRONMENT=Docker
  ports:
      - "4040:4040"

services:
  server:
    <<: *default-service
    container_name: sokka_server
    build:
      context: .
      dockerfile: src/Sokka.Server/Dockerfile

  client:
    <<: *default-service
    container_name: sokka_client
    build:
      context: .
      dockerfile: src/Sokka.Client/Dockerfile
